Iryna-Holova/project-devteam-01

- src/components/CategoriesPreview/CategoriesList/CategoriesList.jsx
- src/components/CategoriesPreview/CategoriesPreview.jsx
- src/components/HeroMain/ChooseBreakfast/ChooseBreakfast.styled.jsx
- src/pages/Main.jsx
Deleted empty files from redux(from old commits), moved  main page logic from components to main page
> Refactoring of main page and clean up of code

- src/components/App.jsx
- src/hooks/useCategories.js
- src/hooks/useMainPage.js
- src/hooks/useSearchByCategory.js
- src/hooks/useSearchByName.js
- src/pages/Test.jsx
- src/redux/Categories/operations.js
- src/redux/Categories/selectors.js
- src/redux/Categories/slice.js
- src/redux/Recipes/favorite/favoriteRecipesOperations.js
- src/redux/Recipes/favorite/favoriteRecipesSelectors.js
- src/redux/Recipes/favorite/favoriteRecipesSlice.js
- src/redux/Recipes/main-page/operations.js
- src/redux/Recipes/main-page/selectors.js
- src/redux/Recipes/main-page/slice.js
- src/redux/Recipes/reducer.js
- src/redux/Recipes/searchByCategory/operations.js
- src/redux/Recipes/searchByCategory/selectors.js
- src/redux/Recipes/searchByCategory/slice.js
- src/redux/Recipes/searchByName/operations.js
- src/redux/Recipes/searchByName/selectors.js
- src/redux/Recipes/searchByName/slice.js
- src/redux/auth/operations.js
- src/redux/store.js
- src/services/api/recipes-api.js
Реаллизованы запросы для mainpage, поиску по тайтлу, по категории, список категорий.
> new branch from main with redux code

- src/components/Searchbar/Searchbar.jsx
- src/components/Searchbar/Searchbar.styled.jsx
- src/pages/Search.jsx
- src/services/getIngredientsRecipes.js
- src/services/getTitleRecipes.js
> Search bar

- src/pages/Search.jsx
- src/pages/Test.jsx
- src/redux/Categories/slice.js
- src/redux/Recipes/main-page/slice.js
- src/redux/Recipes/reducer.js
- src/redux/store.js
- src/services/api/recipes-api.js
Почистил код, чтобы прошел билд
> comment or delete unused code

- src/hooks/useSearchBy.js
- src/pages/Test.jsx
- src/redux/Recipes/SearchBy/operations.js
- src/redux/Recipes/SearchBy/selectors.js
- src/redux/Recipes/SearchBy/slice.js
- src/redux/Recipes/reducer.js
- src/services/api/recipes-api/index.js
- src/services/api/recipes-api/ingredients.js
- src/utils/constants.js
Добавлен slice SearchBy в котором реализован поиск по тайтлу или индредиенту в зависимости от выставленного свойства method.
> ADDED searchBy slice, getRecipesByIngredient api function

- src/components/Footer/Nav/Nav.styled.jsx
- src/components/Header/Header.jsx
- src/components/Header/Header.styled.jsx
Поки що додав те що є. Ще треба багато зробити і переробити. Збираю все до купи. Як відправлю останню версію, напишу.
> test update header

- src/redux/Ingredients/selectors.js
add export to Ingredients selectors
> add export to selectors

- src/components/App.jsx
Change reaction on window resize. dispatching only then device changed. Also set Limit to all slises in store where it need.
> add setLimit on resize event

- src/assets/svg/MainPage/GreenArrowDesktop.svg
- src/assets/svg/MainPage/arrow-narrow-right.svg
- src/assets/svg/MainPage/arrowMainPage.svg
- src/components/CategoriesPreview/CategoriesPreview.jsx
- src/components/CategoriesPreview/CategoriesPreview.styled.jsx
- src/components/HeroMain/ChooseBreakfast/ChooseBreakfast.jsx
- src/components/HeroMain/ChooseBreakfast/ChooseBreakfast.styled.jsx
- src/components/HeroMain/HeroMain.jsx
- src/components/HeroMain/HeroMain.styled.jsx
Adapted images for retina, added arrow and improved styles for main page
> Images and Styles for Main Page

- src/components/App.jsx
fix error in promise.all in app
> fix error in promise.all in app

- package-lock.json
- package.json
- src/components/AddRecipePage/AddRecipeForm.jsx
- src/components/AddRecipePage/AddRecipeForm.styled.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipeDescription/RecipeDescription.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipeDescription/RecipeDescription.styled.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipeIngredients/RecipeIngredients.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipeIngredients/RecipeIngredients.styled.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipePreparation/RecipePreparation.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipePreparation/RecipePreparation.styled.jsx
- src/pages/AddRecipe.jsx
- src/services/api/recipes-api/own.js
3 components working and sending data as formData
Still in progress unfilled check boxes in trello - AddRecipePage /add
> AddRecipeForm

- src/components/CategoriesPreview/CategoriesList/CategoriesList.styled.jsx
- src/components/CategoriesPreview/CategoriesPreview.styled.jsx
- src/components/HeroMain/ChooseBreakfast/ChooseBreakfast.styled.jsx
- src/components/Searchbar/Searchbar.jsx
- src/components/Searchbar/Searchbar.styled.jsx
- src/index.css
- src/pages/Main.jsx
- src/pages/Search.jsx
Improved styles for searchbar and improved logic of search page
> Improved styles for searchbar and improved logic of search page

- src/components/Searchbar/Searchbar.jsx
- src/components/Searchbar/Searchbar.styled.jsx
- src/pages/Search.jsx
> added NoDataMessage and Loader to Search page, 

- src/components/ShoppingList/IngredientsShoppingList.jsx
Закоментриовал и удалил ненужные импорты
> deleted unused const and imports

- src/pages/Favorite.jsx
- src/redux/Recipes/favorite/operations.js
- src/redux/Recipes/favorite/selectors.js
- src/redux/Recipes/favorite/slice.js
> fix empty favorite page

- src/components/Searchbar/Searchbar.jsx
- src/components/Searchbar/Searchbar.styled.jsx
- src/pages/Main.jsx
- src/pages/Search.jsx
DONE: Fixed search by when looking for something from main, search by title and ingredients.
TODO: fix some bugs.
> fixed search in search and main page

- src/hooks/use-auth.js
- src/redux/auth/operations.js
- src/redux/auth/selectors.js
- src/redux/auth/slice.js
added fild error in Auth slice whith error message from back
const {error,isError} = useAuth();
> added filed error in Auth slice

- src/components/CategoriesPreview/CategoriesList/CategoriesList.jsx
- src/components/Searchbar/Searchbar.jsx
- src/pages/Search.jsx
uncommented searchParams in searchBar to enable search
> added topScroll to main, 

- src/components/AddRecipePage/AddRecipeForm.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipeDescription/RecipeDescription.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipeDescription/RecipeDescription.styled.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipeIngredients/RecipeIngredients.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipeIngredients/RecipeIngredients.styled.jsx
- src/components/AddRecipePage/AddRecipeForm/RecipePreparation/RecipePreparation.jsx
image resize and validation in progress
> react-select working

- src/components/Header/EditProfileModal/EditProfileModal.jsx
- src/redux/auth/operations.js
- src/redux/auth/slice.js
Исправлено обновление профиля пользователя на сервере и в редаксе.
> fixed updating user photo, added operation updateUser

- src/pages/Recipe.jsx
Исправлена ошибка на странице рецепта, когда несколько раз нажимаешь на кнопку добавления\удаления в избранные
> fixed error then add or remove recipe to/from favorite

- src/components/Searchbar/Searchbar.jsx
- src/hooks/useDebounce.js
- src/pages/Search.jsx
- src/redux/Recipes/SearchBy/selectors.js
- src/utils/debounce.js
- src/utils/index.js
1. Исправил ошибку с бесконечным запуском запроса.
2. Изменил определение устройства на 1280
> add debounce func and hook, fix problems on search

- src/hooks/useDebounce.js
add dependency 'wait' to useMemo in hook useDebounce
> add dependency to useMemo in useDebounce
